// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void test1() {
    driver.get("https://www.tutorialspoint.com/index.htm");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.linkText("Login")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.id("btnGoogleLogin")).click();
    vars.put("win1885", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win1885").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.linkText("Certifications")).click();
    driver.findElement(By.linkText("New Arrivals")).click();
    driver.findElement(By.linkText("Dashboard")).click();
    {
      WebElement element = driver.findElement(By.linkText("Dashboard"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("SQL"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("SQL")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,379.3333435058594)");
    js.executeScript("window.scrollTo(0,527.3333129882812)");
    js.executeScript("window.scrollTo(0,839.3333129882812)");
    js.executeScript("window.scrollTo(0,1067.3333740234375)");
    js.executeScript("window.scrollTo(0,1657.3333740234375)");
    js.executeScript("window.scrollTo(0,1832)");
    js.executeScript("window.scrollTo(0,1833.3333740234375)");
    driver.findElement(By.cssSelector(".toggle:nth-child(71) > .toggle__toggle")).click();
    driver.findElement(By.cssSelector(".toggle:nth-child(72) img")).click();
    driver.findElement(By.cssSelector(".toggle:nth-child(76) img")).click();
    driver.findElement(By.cssSelector(".toggle:nth-child(74) img")).click();
    driver.findElement(By.cssSelector("a:nth-child(2) > .button")).click();
    js.executeScript("window.scrollTo(0,264)");
    js.executeScript("window.scrollTo(0,646)");
    js.executeScript("window.scrollTo(0,259.3333435058594)");
    driver.findElement(By.cssSelector(".library-page-top-nav > a > .button")).click();
    driver.findElement(By.linkText("HTML")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("HTML - Basic Tags")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("HTML - Fonts")).click();
    {
      WebElement element = driver.findElement(By.linkText("HTML - Quotations"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("HTML - Quotations")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,754)");
    driver.findElement(By.cssSelector("a:nth-child(2) > .button")).click();
    driver.findElement(By.linkText("Javascript")).click();
    js.executeScript("window.scrollTo(0,176)");
    js.executeScript("window.scrollTo(0,206)");
    js.executeScript("window.scrollTo(0,1436)");
    driver.findElement(By.cssSelector(".toc:nth-child(3) > li:nth-child(4)")).click();
    driver.findElement(By.linkText("JavaScript - Features")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("JavaScript - Comments")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("JavaScript - Constants")).click();
    driver.findElement(By.linkText("JavaScript - While Loop")).click();
    driver.findElement(By.linkText("SQL")).click();
    driver.findElement(By.linkText("Python")).click();
    {
      WebElement element = driver.findElement(By.linkText("C"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("C")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("C++")).click();
    driver.findElement(By.linkText("Scala")).click();
    driver.findElement(By.linkText("C#")).click();
    driver.findElement(By.linkText("MySQL")).click();
    driver.findElement(By.linkText("MongoDB")).click();
    js.executeScript("window.scrollTo(0,471.3333435058594)");
    {
      WebElement element = driver.findElement(By.cssSelector(".tp-btn:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,471.3333435058594)");
    js.executeScript("window.scrollTo(0,1401.3333740234375)");
    js.executeScript("window.scrollTo(0,1968)");
    driver.findElement(By.linkText("MongoDB - Sorting Records")).click();
    driver.findElement(By.linkText("MongoDB - Insert Document")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("MongoDB - Capped Collections")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("C")).click();
    driver.findElement(By.id("search-strings")).click();
    driver.findElement(By.id("search-strings")).sendKeys("java");
    driver.findElement(By.id("search-strings")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("search-strings")).sendKeys("java");
    driver.findElement(By.id("search-strings")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("li:nth-child(4) > .filter-aside__sublist > .checkbox:nth-child(1) > .checkmark")).click();
    driver.findElement(By.id("search-strings")).click();
    driver.findElement(By.id("search-strings")).sendKeys("angular");
    driver.findElement(By.id("search-strings")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("#category-div > .checkbox:nth-child(3) > .checkmark")).click();
    driver.findElement(By.cssSelector(".select__toggle")).click();
    driver.findElement(By.id("3")).click();
    driver.findElement(By.cssSelector("a:nth-child(8)")).click();
    driver.findElement(By.cssSelector("#category-div > .checkbox:nth-child(2) > .checkmark")).click();
    driver.findElement(By.cssSelector(".dropdown__toggle")).click();
    driver.findElement(By.linkText("Cyber Security")).click();
    driver.findElement(By.linkText("Home")).click();
    {
      WebElement element = driver.findElement(By.linkText("Javascript"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Python"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Scala")).click();
    js.executeScript("window.scrollTo(0,298)");
    js.executeScript("window.scrollTo(0,671.3333129882812)");
    js.executeScript("window.scrollTo(0,976)");
    driver.findElement(By.cssSelector("a:nth-child(2) > .button")).click();
    js.executeScript("window.scrollTo(0,308)");
    js.executeScript("window.scrollTo(0,738)");
    js.executeScript("window.scrollTo(0,1853.3333740234375)");
    driver.findElement(By.cssSelector("a:nth-child(2) > .button")).click();
    driver.findElement(By.linkText("Node.js")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".videolink > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".toc > li:nth-child(19)")).click();
    driver.findElement(By.linkText("Node.js - Scaling Application")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("Node.js - Callbacks Concept")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".dropdown__toggle")).click();
    driver.findElement(By.cssSelector(".category-button:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".category-button:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".category-button:nth-child(4)")).click();
    driver.findElement(By.linkText("GIT")).click();
    js.executeScript("window.scrollTo(0,152)");
    js.executeScript("window.scrollTo(0,199.3333282470703)");
    driver.findElement(By.cssSelector(".toc > li:nth-child(12)")).click();
    driver.findElement(By.cssSelector(".foot-links-navigate > a:nth-child(3)")).click();
    js.executeScript("window.scrollTo(0,206)");
    js.executeScript("window.scrollTo(0,307.3333435058594)");
    driver.findElement(By.linkText("Fresher Entry Level")).click();
    js.executeScript("window.scrollTo(0,165.3333282470703)");
    {
      WebElement element = driver.findElement(By.cssSelector(".h-item:nth-child(1) .mt1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Part Time")).click();
    js.executeScript("window.scrollTo(0,271.3333435058594)");
    js.executeScript("window.scrollTo(0,413.3333435058594)");
    js.executeScript("window.scrollTo(0,591.3333129882812)");
    js.executeScript("window.scrollTo(0,786)");
    driver.findElement(By.linkText("Online Freelance")).click();
    js.executeScript("window.scrollTo(0,259.3333435058594)");
    js.executeScript("window.scrollTo(0,464)");
    js.executeScript("window.scrollTo(0,718)");
    driver.findElement(By.linkText("Library")).click();
    js.executeScript("window.scrollTo(0,21.33333396911621)");
    js.executeScript("window.scrollTo(0,212)");
    driver.findElement(By.cssSelector(".top-categories__button-next")).click();
    driver.findElement(By.linkText("See All")).click();
    js.executeScript("window.scrollTo(0,124)");
    js.executeScript("window.scrollTo(0,460)");
    driver.findElement(By.linkText("SAP Tutorials")).click();
    js.executeScript("window.scrollTo(0,77.33333587646484)");
    js.executeScript("window.scrollTo(0,167.3333282470703)");
    js.executeScript("window.scrollTo(0,168)");
    driver.switchTo().frame(12);
    driver.findElement(By.cssSelector("#cbb path:nth-child(1)")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector(".col-md-3:nth-child(1) img")).click();
    js.executeScript("window.scrollTo(0,177.3333282470703)");
    js.executeScript("window.scrollTo(0,518)");
    js.executeScript("window.scrollTo(0,990)");
    driver.findElement(By.linkText("Crystal Reports - Page Layout")).click();
    js.executeScript("window.scrollTo(0,700)");
    js.executeScript("window.scrollTo(0,1245.3333740234375)");
    driver.findElement(By.linkText("Crystal Reports - Inserting Objects")).click();
    js.executeScript("window.scrollTo(0,954)");
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".library-nav__container")).click();
    driver.findElement(By.id("scroll_right_btn")).click();
    driver.findElement(By.id("scroll_right_btn")).click();
    driver.findElement(By.id("scroll_right_btn")).click();
    driver.findElement(By.id("scroll_right_btn")).click();
    driver.findElement(By.id("scroll_right_btn")).click();
    driver.findElement(By.id("scroll_right_btn")).click();
    driver.findElement(By.id("scroll_right_btn")).click();
    driver.findElement(By.id("scroll_right_btn")).click();
    driver.findElement(By.id("scroll_right_btn")).click();
    driver.findElement(By.id("scroll_right_btn")).click();
    driver.findElement(By.linkText("R")).click();
    js.executeScript("window.scrollTo(0,262)");
    js.executeScript("window.scrollTo(0,366)");
    driver.findElement(By.linkText("Blockchain")).click();
    js.executeScript("window.scrollTo(0,213.3333282470703)");
    js.executeScript("window.scrollTo(0,530)");
    driver.findElement(By.linkText("Smart Contracts in Blockchain")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.linkText("How Bitcoin Works?")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".library-page-top-nav > .flex-group .button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".library-page-top-nav > .flex-group .button")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    js.executeScript("window.scrollTo(0,1105.3333740234375)");
    js.executeScript("window.scrollTo(0,1695.3333740234375)");
    js.executeScript("window.scrollTo(0,3260)");
    {
      WebElement element = driver.findElement(By.cssSelector("a:nth-child(2) > .button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("a:nth-child(2) > .button")).click();
    driver.findElement(By.cssSelector(".library-page-top-nav > a > .button")).click();
    {
      WebElement element = driver.findElement(By.linkText("Java"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".library-page-top-nav > .flex-group .button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Whiteboard")).click();
    driver.findElement(By.linkText("Coding Ground")).click();
    {
      WebElement element = driver.findElement(By.linkText("Java"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".swiper-slide:nth-child(4) img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".swiper-slide:nth-child(4) img")).click();
    vars.put("win2304", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win2304").toString());
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    js.executeScript("window.scrollTo(0,78)");
    {
      WebElement element = driver.findElement(By.linkText("Scala"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Scala")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Cloud Computing Tutorial")).click();
    {
      WebElement element = driver.findElement(By.linkText("MongoDB"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Certifications")).click();
    driver.findElement(By.id("showMore")).click();
    driver.findElement(By.id("showMore")).click();
    driver.findElement(By.linkText("eBooks")).click();
    driver.findElement(By.cssSelector(".dropdown__toggle")).click();
    driver.findElement(By.linkText("Finance and Accounting")).click();
    driver.findElement(By.linkText("Cyber security")).click();
    driver.findElement(By.linkText("Marketing")).click();
    driver.findElement(By.linkText("Business")).click();
    driver.findElement(By.linkText("IT and Software")).click();
    driver.findElement(By.linkText("Lifestyle")).click();
    driver.findElement(By.linkText("Office Productivity")).click();
    driver.findElement(By.linkText("Lifestyle")).click();
    driver.findElement(By.linkText("Office Productivity")).click();
    driver.findElement(By.linkText("Corporate Training")).click();
    driver.findElement(By.id("divContain")).click();
    driver.findElement(By.cssSelector(".dd-menu > ul:nth-child(1) > li:nth-child(5) > a")).click();
    driver.findElement(By.id("divContain1")).click();
    driver.findElement(By.cssSelector(".dropdown__item:nth-child(2) span")).click();
    driver.findElement(By.cssSelector("li:nth-child(3) > .filter-aside__sublist > .checkbox:nth-child(3)")).click();
    driver.findElement(By.cssSelector("li:nth-child(3) > .filter-aside__sublist > .checkbox:nth-child(3) > .checkmark")).click();
    driver.findElement(By.name("video_duration")).click();
  }
}
